import type { KitDefinition } from './types';

/** Coach / consultant: sober, ivory paper, deep teal ink, serif titles, thin rules — nothing shouts. */
export const cabinet: KitDefinition = {
  id: 'cabinet',
  name: 'Cabinet',
  pitch: 'Sobre et posé : papier ivoire, titres en serif, filets fins et un seul vert profond.',
  universe: 'Coach, consultant',
  goals: ['capture', 'vente', 'webinaire'],
  tokens: {
    bg: '#faf7f2', alt: '#f1ece3', surface: '#ffffff', text: '#1c2733', muted: '#55606c',
    accent: '#14524f', accentText: '#ffffff', accentInk: '#14524f', accent2: '#b07e3f', border: '#ddd5c8',
    inverse: '#16222e', inverseText: '#f6f1e8', inverseMuted: '#b6c0ca', inverseAccent: '#e2b877',
    fontHeading: "Lora, Georgia, 'Times New Roman', serif", fontBody: "Figtree, 'Helvetica Neue', Arial, sans-serif",
    radius: 6, buttonRadius: 4, shadow: 'none', headingWeight: 600, headingSpacing: -0.4,
    h1: 52, h2: 34, lead: 19, space: 88, width: 1040,
  },
  layout: {
    align: 'left', eyebrow: 'rule', header: 'bar', hero: 'split', benefits: 'rows', proof: 'quote', offer: 'split', cta: 'line', footer: 'plain',
    art: 'frames', emailHeader: 'left', emailHero: 'plain',
  },
  copy: {
    brand: 'Hélène Marchal',
    tagline: 'Conseil et accompagnement de dirigeants',
    sign: 'Bien à vous,\n**Hélène Marchal**',
    magnet: {
      eyebrow: 'Diagnostic offert',
      title: 'Douze questions pour y voir clair avant votre prochaine décision',
      lead: 'Un questionnaire à remplir seul, au calme, pour distinguer ce qui relève de l’urgence de ce qui compte vraiment.',
      bullets: ['Un document de travail, pas une lecture de plus', 'Vingt minutes suffisent pour le compléter', 'Une grille de lecture pour interpréter vos réponses'],
      formTitle: 'Recevoir le diagnostic',
      cta: 'Recevoir le diagnostic',
      note: 'Envoyé par email. Vos coordonnées ne sont jamais transmises.',
    },
    offer: {
      name: 'Cap 90',
      eyebrow: 'Accompagnement individuel',
      title: 'Quatre-vingt-dix jours pour reprendre la main sur votre activité',
      lead: 'Un cadre de travail, six entretiens et un plan que vous tiendrez : l’accompagnement des dirigeants qui veulent décider mieux, pas travailler plus.',
      cta: 'Réserver un premier échange',
      story: ['Vous n’avez pas un problème de temps', 'Vous avez une liste de décisions repoussées. Chacune semble raisonnable à reporter ; ensemble, elles occupent tout l’espace. Cap 90 sert à les traiter une à une, dans l’ordre qui compte, avec quelqu’un qui vous pose les bonnes questions.'],
      benefitsTitle: 'Ce qui change en trois mois',
      benefits: [
        ['Des priorités que vous pouvez défendre', 'Trois chantiers, pas douze. Vous savez pourquoi vous dites non au reste.'],
        ['Des décisions prises à temps', 'Chaque entretien se conclut par une décision datée, puis par son suivi.'],
        ['Un rythme qui tient sans vous épuiser', 'Une semaine type construite à partir de votre énergie réelle, pas d’un idéal.'],
      ],
      programTitle: 'Le déroulé',
      program: [
        ['Semaines 1 à 2 — État des lieux', 'Nous cartographions vos engagements, vos marges et ce qui vous retient.'],
        ['Semaines 3 à 10 — Les chantiers', 'Un entretien toutes les deux semaines, un compte rendu écrit, des actions courtes.'],
        ['Semaines 11 à 13 — L’ancrage', 'Nous installons les rituels qui feront durer ce que vous avez mis en place.'],
      ],
      includes: ['Six entretiens individuels d’une heure', 'Un compte rendu écrit après chaque séance', 'Un accès par message entre les entretiens', 'Votre feuille de route à 90 jours'],
      priceNote: 'paiement en une ou trois fois',
      guarantee: 'Si le premier entretien ne vous convainc pas, l’accompagnement s’arrête là et vous êtes remboursé.',
      faq: [
        { q: 'À qui s’adresse Cap 90 ?', a: 'Aux dirigeants et indépendants installés qui ont une activité en marche et le sentiment de la subir.' },
        { q: 'Comment se passent les entretiens ?', a: 'En visioconférence ou au cabinet, à des créneaux fixés ensemble dès le départ.' },
        { q: 'Combien de temps faut-il prévoir ?', a: 'Une heure d’entretien toutes les deux semaines, et une à deux heures de travail personnel entre deux.' },
        { q: 'Et si je dois décaler une séance ?', a: 'Chaque séance peut être reportée une fois, en prévenant 48 heures à l’avance.' },
      ],
      finalTitle: 'Commençons par une conversation',
      finalText: 'Trente minutes pour voir si ce cadre vous correspond. Sans engagement.',
    },
    upsell: {
      title: 'Ajoutez la journée de travail en présentiel',
      text: 'Une journée entière au cabinet pour poser votre feuille de route à plat, loin du quotidien.',
      bullets: ['Une journée de travail à deux', 'Votre plan à 12 mois, rédigé ensemble', 'À planifier dans les trois premiers mois'],
      accept: 'Oui, j’ajoute la journée de travail',
      decline: 'Non merci, je m’en tiens à Cap 90',
    },
    thanks: {
      title: 'Merci {{first_name}}, c’est noté',
      lead: 'Votre demande est enregistrée. Voici comment les choses vont se passer.',
      steps: [
        ['Un email de confirmation', 'Il arrive dans quelques minutes. Pensez à regarder vos courriers indésirables.'],
        ['Votre document', 'Vous le trouverez en pièce jointe ; gardez-le sous la main pour notre échange.'],
        ['Un premier échange', 'Si vous le souhaitez, répondez à l’email pour convenir d’un créneau.'],
      ],
    },
    webinar: {
      eyebrow: 'Conférence en ligne',
      title: 'Décider sous pression : une méthode en trois temps',
      lead: 'Quarante-cinq minutes pour apprendre à trancher quand tout semble urgent, suivies de vos questions.',
      when: '[Jour et date] à [heure] — en ligne',
      points: [
        ['Trier', 'Distinguer une décision d’une simple inquiétude.'],
        ['Instruire', 'Réunir ce qu’il faut savoir, et rien de plus.'],
        ['Trancher', 'Fixer une date, un critère et un responsable.'],
      ],
      hostName: 'Animée par Hélène Marchal',
      hostBio: '[Présentez-vous en trois lignes : votre parcours, les personnes que vous accompagnez, ce qui fonde votre méthode.]',
      cta: 'Réserver ma place',
    },
    soon: {
      eyebrow: 'Prochaine session',
      title: 'Les inscriptions à Cap 90 rouvrent bientôt',
      lead: 'Les places sont limitées par le nombre d’entretiens que je peux assurer. Laissez votre adresse pour être averti à l’ouverture.',
      cta: 'Me prévenir à l’ouverture',
    },
    voices: [
      { quote: '[Témoignage à remplacer] En deux phrases : la situation de votre client avant l’accompagnement, puis ce qu’il décide autrement aujourd’hui.', name: 'Prénom N.', role: 'Fonction, entreprise' },
      { quote: '[Témoignage à remplacer] Un résultat concret et vérifiable, dit avec les mots du client.', name: 'Prénom N.', role: 'Fonction, entreprise' },
      { quote: '[Témoignage à remplacer] Ce que le client dirait à un pair qui hésite.', name: 'Prénom N.', role: 'Fonction, entreprise' },
    ],
    emails: {
      welcome: {
        subject: 'Votre diagnostic, et la suite',
        preheader: 'Le document est en pièce jointe, voici comment l’utiliser.',
        title: 'Bienvenue, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nMerci de votre confiance. Vous trouverez le diagnostic ci-dessous. Prenez-le comme un temps de travail : un carnet, vingt minutes, la porte fermée.',
        steps: ['Répondez aux douze questions sans vous relire', 'Laissez reposer une journée', 'Relisez avec la grille d’interprétation'],
        cta: 'Ouvrir le diagnostic',
      },
      newsletter: {
        subject: 'La lettre du cabinet — décider moins, décider mieux',
        preheader: 'Une idée, un outil, une question pour votre semaine.',
        issue: 'La lettre du cabinet',
        title: 'Ce que vous décidez de ne pas faire',
        body: 'Bonjour {{first_name}},\n\nUne stratégie se lit d’abord dans ce qu’elle écarte. Cette semaine, je vous propose un exercice simple : noter trois choses que vous cessez de faire, et à qui vous l’annoncez.',
        cta: 'Lire l’article',
        shorts: [['L’outil de la semaine', 'La liste des « pas maintenant » : une page, relue chaque vendredi.'], ['La question à emporter', 'Quelle décision attend depuis plus de trente jours ?']],
        quote: 'Renoncer, c’est aussi décider.',
      },
      promo: {
        subject: 'Cap 90 : les inscriptions sont ouvertes',
        preheader: 'Six entretiens, un plan, quatre-vingt-dix jours.',
        eyebrow: 'Inscriptions ouvertes',
        title: 'Cap 90 reprend le [date]',
        body: 'Bonjour {{first_name}},\n\nLa prochaine session de Cap 90 démarre bientôt. Si vous repoussez depuis des mois les mêmes décisions, c’est le bon cadre pour les traiter.',
        points: ['Six entretiens individuels', 'Un compte rendu écrit après chaque séance', 'Votre feuille de route à 90 jours'],
        cta: 'Réserver un premier échange',
        ps: 'P.-S. Le premier échange dure trente minutes et ne vous engage à rien.',
      },
      reminder: {
        subject: 'Dernier jour pour rejoindre Cap 90',
        preheader: 'Les inscriptions ferment ce soir.',
        body: 'Bonjour {{first_name}},\n\nUn mot bref : les inscriptions à Cap 90 ferment ce soir. Si vous hésitez encore, répondez-moi directement — je vous dirai franchement si ce cadre est fait pour vous.',
        cta: 'Réserver un premier échange',
        ps: 'P.-S. La session suivante n’est pas encore datée.',
      },
      webinar: {
        subject: 'Votre place est réservée',
        preheader: 'Date, lien de connexion et préparation.',
        title: 'Votre place est réservée, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nVous êtes inscrit à la conférence « Décider sous pression ». Voici les informations pratiques.',
        tips: ['Notez une décision que vous repoussez', 'Prévoyez de quoi écrire', 'Connectez-vous cinq minutes avant'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
