import type { KitDefinition } from './types';

/** Wellness: soft and round — blush paper, plum ink, tall delicate serif, pill buttons, breathing space. */
export const douceur: KitDefinition = {
  id: 'douceur',
  name: 'Douceur',
  pitch: 'Doux et rond : papier rosé, encre prune, serif délié, boutons pilule et beaucoup d’air.',
  universe: 'Bien-être, soin, yoga',
  goals: ['capture', 'vente', 'webinaire'],
  tokens: {
    bg: '#fdf8f4', alt: '#f6e9e1', surface: '#fffdfb', text: '#43313a', muted: '#6c5760',
    accent: '#7a4f5f', accentText: '#ffffff', accentInk: '#7a4f5f', accent2: '#d9a58f', border: '#e6d3c8',
    inverse: '#4a3540', inverseText: '#fdf3ec', inverseMuted: '#d9c3c9', inverseAccent: '#f3cdb8',
    fontHeading: "'Cormorant Garamond', Georgia, 'Times New Roman', serif", fontBody: "Nunito, 'Helvetica Neue', Arial, sans-serif",
    radius: 28, buttonRadius: 999, shadow: 'none', headingWeight: 600, headingSpacing: 0, buttonWeight: 700,
    h1: 62, h2: 42, lead: 19, space: 96, width: 960,
  },
  layout: {
    align: 'center', eyebrow: 'caps', header: 'center', hero: 'center', benefits: 'grid', proof: 'quote', offer: 'card', cta: 'boxed', footer: 'plain',
    art: 'blobs', emailHeader: 'center', emailHero: 'card',
  },
  copy: {
    brand: 'Maison Alba',
    tagline: 'Respiration, yoga doux et temps pour soi',
    sign: 'Avec douceur,\n**Inès, de Maison Alba**',
    magnet: {
      eyebrow: 'Sept jours offerts',
      title: 'Sept respirations guidées pour ralentir',
      lead: 'Un audio de cinq minutes chaque matin pendant une semaine. À écouter assise, debout, ou encore au lit.',
      bullets: ['Cinq minutes, pas une de plus', 'Aucune expérience nécessaire', 'À écouter où vous voulez'],
      formTitle: 'Recevoir la première respiration',
      cta: 'Je commence demain matin',
      note: 'Un email par jour pendant sept jours, puis plus rien sans votre accord.',
    },
    offer: {
      name: 'Souffle',
      eyebrow: 'Programme de quatre semaines',
      title: 'Quatre semaines pour retrouver un souffle calme',
      lead: 'Des pratiques courtes, guidées à la voix, pour installer un vrai rituel — sans bousculer vos journées.',
      cta: 'Je rejoins Souffle',
      story: ['Vous n’avez pas besoin d’une heure de plus', 'Vous avez besoin de cinq minutes qui comptent. Souffle n’ajoute rien à votre liste : il transforme des moments que vous avez déjà — le réveil, une pause, le coucher — en points d’appui.'],
      benefitsTitle: 'Ce que ces quatre semaines installent',
      benefits: [
        ['Un réveil plus doux', 'Une pratique de cinq minutes pour commencer la journée posée.'],
        ['Des pauses qui reposent', 'Trois respirations à glisser entre deux rendez-vous.'],
        ['Un sommeil apaisé', 'Un rituel du soir pour déposer la journée.'],
      ],
      programTitle: 'Semaine après semaine',
      program: [
        ['Semaine 1 — Observer', 'Apprendre à sentir son souffle sans le forcer.'],
        ['Semaine 2 — Allonger', 'Des expirations longues pour relâcher.'],
        ['Semaine 3 — Ancrer', 'Relier le souffle au mouvement.'],
        ['Semaine 4 — Garder', 'Composer votre rituel personnel.'],
      ],
      includes: ['Vingt-huit pratiques audio guidées', 'Un carnet de bord à imprimer', 'Une séance collective en ligne chaque semaine', 'L’accès aux enregistrements pendant un an'],
      priceNote: 'paiement unique',
      guarantee: 'Essayez la première semaine : si Souffle ne vous convient pas, vous êtes remboursée.',
      faq: [
        { q: 'Je n’ai jamais pratiqué. Est-ce pour moi ?', a: 'Oui. Tout est guidé pas à pas, et chaque pratique propose une variante plus simple.' },
        { q: 'Quand dois-je pratiquer ?', a: 'Quand vous voulez. Les audios sont courts et disponibles à tout moment.' },
        { q: 'Et si je manque un jour ?', a: 'Vous reprenez là où vous en étiez. Rien ne se perd, rien ne presse.' },
        { q: 'Y a-t-il des contre-indications ?', a: '[Précisez ici les précautions à prendre et invitez à demander un avis médical en cas de doute.]' },
      ],
      finalTitle: 'Offrez-vous cinq minutes par jour',
      finalText: 'Le prochain cycle commence le [date]. Vous pouvez aussi démarrer quand vous le souhaitez.',
    },
    upsell: {
      title: 'Ajoutez les méditations du soir',
      text: 'Dix audios plus longs, pour les soirs où vous avez un peu plus de temps.',
      bullets: ['Dix méditations de quinze minutes', 'À télécharger et à garder', 'Une voix, pas de musique imposée'],
      accept: 'Oui, j’ajoute les méditations',
      decline: 'Non merci, pas pour le moment',
    },
    thanks: {
      title: 'Merci {{first_name}}, tout est prêt',
      lead: 'Votre inscription est confirmée. Prenez une grande inspiration — voici la suite.',
      steps: [
        ['Regardez vos emails', 'Votre premier audio arrive dans quelques minutes.'],
        ['Choisissez votre moment', 'Le matin, à midi ou le soir : l’important est qu’il soit le même.'],
        ['Installez-vous', 'Un coussin, une chaise, un coin tranquille suffisent.'],
      ],
    },
    webinar: {
      eyebrow: 'Séance découverte en ligne',
      title: 'Une heure pour apprendre à relâcher',
      lead: 'Une séance guidée en direct, accessible à toutes, suivie d’un temps d’échange.',
      when: '[Jour et date] à [heure] — en ligne',
      points: [
        ['S’installer', 'Trouver une posture confortable, chez soi.'],
        ['Respirer', 'Trois pratiques simples, guidées à la voix.'],
        ['Emporter', 'Un mini-rituel à refaire seule.'],
      ],
      hostName: 'Guidée par Inès',
      hostBio: '[Trois lignes sur votre parcours, votre formation et ce que vous aimez transmettre.]',
      cta: 'Je réserve ma place',
    },
    soon: {
      eyebrow: 'Prochain cycle',
      title: 'Un nouveau cycle s’ouvre bientôt',
      lead: 'Laissez votre adresse : vous serez la première informée de la date d’ouverture.',
      cta: 'Me prévenir',
    },
    voices: [
      { quote: '[Témoignage à remplacer] Ce que votre élève ressent de différent, avec ses mots.', name: 'Prénom N.', role: 'Élève du programme' },
      { quote: '[Témoignage à remplacer] Le moment de la journée qui a changé pour elle.', name: 'Prénom N.', role: 'Élève du programme' },
      { quote: '[Témoignage à remplacer] Ce qu’elle dirait à une amie.', name: 'Prénom N.', role: 'Élève du programme' },
    ],
    emails: {
      welcome: {
        subject: 'Votre première respiration',
        preheader: 'Cinq minutes, juste pour vous.',
        title: 'Bienvenue, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nMerci de nous rejoindre. Votre première respiration guidée vous attend. Installez-vous confortablement, et laissez-vous porter.',
        steps: ['Trouvez un endroit calme', 'Lancez l’audio', 'Notez un mot sur ce que vous ressentez'],
        cta: 'Écouter la première respiration',
      },
      newsletter: {
        subject: 'La lettre lente — respirer avant de répondre',
        preheader: 'Une pratique, une lecture, une pensée.',
        issue: 'La lettre lente',
        title: 'Respirer avant de répondre',
        body: 'Bonjour {{first_name}},\n\nEntre ce qu’on nous demande et ce qu’on répond, il y a la place d’une respiration. Ce mois-ci, je vous propose de l’habiter.',
        cta: 'Lire la suite',
        shorts: [['La pratique du mois', 'Trois expirations longues avant chaque appel.'], ['Dans ma bibliothèque', '[Un livre ou un article que vous recommandez.]']],
        quote: 'Le calme ne se trouve pas, il se pratique.',
      },
      promo: {
        subject: 'Souffle : le nouveau cycle est ouvert',
        preheader: 'Quatre semaines pour retrouver un souffle calme.',
        eyebrow: 'Inscriptions ouvertes',
        title: 'Un nouveau cycle de Souffle commence',
        body: 'Bonjour {{first_name}},\n\nLes inscriptions au prochain cycle de Souffle sont ouvertes. Quatre semaines de pratiques courtes pour installer un rituel qui vous ressemble.',
        points: ['Vingt-huit pratiques audio guidées', 'Une séance collective chaque semaine', 'La première semaine remboursée si besoin'],
        cta: 'Je rejoins Souffle',
        ps: 'P.-S. Vous pouvez aussi démarrer plus tard : l’accès reste ouvert un an.',
      },
      reminder: {
        subject: 'Le cycle commence lundi',
        preheader: 'Il reste quelques jours pour nous rejoindre.',
        body: 'Bonjour {{first_name}},\n\nUn petit mot pour vous rappeler que le cycle commence lundi. Si vous hésitez, essayez la première semaine : elle vous dira tout.',
        cta: 'Je rejoins Souffle',
        ps: 'P.-S. Une question ? Répondez à cet email, je vous lis.',
      },
      webinar: {
        subject: 'Votre place pour la séance découverte',
        preheader: 'Le lien, l’heure et de quoi vous installer.',
        title: 'Votre place est réservée',
        body: 'Bonjour {{first_name}},\n\nVous êtes inscrite à la séance découverte. Voici les informations pour nous retrouver.',
        tips: ['Prévoyez une tenue confortable', 'Un coussin ou une chaise suffit', 'Coupez les notifications pendant une heure'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
