import type { KitDefinition } from './types';

/** Local / craft: warm and handmade — kraft paper, terracotta, olive, a soft chunky serif, arched window. */
export const marche: KitDefinition = {
  id: 'marche',
  name: 'Marché',
  pitch: 'Chaleureux et fait main : papier kraft, terre cuite, olive et serif généreux.',
  universe: 'Artisan, commerce local',
  goals: ['capture', 'vente', 'lancement'],
  tokens: {
    bg: '#f7efdf', alt: '#ecdfc6', surface: '#fffaf0', text: '#33241a', muted: '#5f4a3a',
    accent: '#a8401f', accentText: '#fff8ec', accentInk: '#8a3315', accent2: '#73803c', border: '#d6c3a1',
    inverse: '#33241a', inverseText: '#f7efdf', inverseMuted: '#cdbba2', inverseAccent: '#e9b872',
    fontHeading: "Fraunces, Georgia, 'Times New Roman', serif", fontBody: "Lato, 'Helvetica Neue', Arial, sans-serif",
    radius: 10, buttonRadius: 6, shadow: 'none', headingWeight: 700, headingSpacing: -0.6, buttonWeight: 700,
    h1: 54, h2: 36, lead: 19, space: 80, width: 1040,
  },
  layout: {
    align: 'left', eyebrow: 'caps', header: 'inverse', hero: 'mirror', benefits: 'grid', proof: 'columns', offer: 'split', cta: 'boxed', footer: 'inverse',
    art: 'arch', emailHeader: 'band', emailHero: 'plain',
  },
  copy: {
    brand: 'Atelier Terre & Feu',
    tagline: 'Céramique artisanale et ateliers, au cœur du quartier',
    sign: 'À bientôt à l’atelier,\n**Margaux**',
    magnet: {
      eyebrow: 'Le carnet de l’atelier',
      title: 'Recevez le calendrier des ateliers avant tout le monde',
      lead: 'Chaque mois, les nouvelles dates, les pièces sorties du four et une astuce pour entretenir vos céramiques.',
      bullets: ['Les dates avant l’ouverture au public', 'Les nouvelles pièces de la boutique', 'Un conseil d’artisan par mois'],
      formTitle: 'Je m’inscris au carnet',
      cta: 'Recevoir le carnet',
      note: 'Un email par mois, écrit à l’atelier.',
    },
    offer: {
      name: 'l’Atelier découverte',
      eyebrow: 'Demi-journée à l’atelier',
      title: 'Tournez votre premier bol, et repartez avec',
      lead: 'Trois heures les mains dans la terre, en petit groupe, avec tout le matériel fourni. Votre pièce est émaillée, cuite, puis vous attend à l’atelier.',
      cta: 'Réserver mon atelier',
      story: ['On n’apprend pas la terre dans un livre', 'Il faut sentir l’argile résister, s’affaisser, puis monter. À l’atelier, on prend le temps : un tour par personne, des gestes montrés un à un, et le droit de recommencer.'],
      benefitsTitle: 'Une demi-journée, trois plaisirs',
      benefits: [
        ['Apprendre un geste', 'Centrer, creuser, monter : les bases du tournage, pas à pas.'],
        ['Créer une pièce', 'Un bol ou une tasse, à votre main, que vous signez.'],
        ['Partager un moment', 'Un petit groupe, du thé, et l’odeur de la terre humide.'],
      ],
      programTitle: 'Le déroulé de l’atelier',
      program: [
        ['L’accueil', 'On enfile un tablier, on découvre la terre et les outils.'],
        ['Le tournage', 'Chacun son tour, et l’artisan à vos côtés.'],
        ['Les finitions', 'Vous choisissez l’émail ; nous nous chargeons de la cuisson.'],
      ],
      includes: ['Trois heures d’atelier en petit groupe', 'La terre, les outils et le tablier', 'L’émaillage et la cuisson de votre pièce', 'Une boisson chaude maison'],
      priceNote: 'par personne, matériel compris',
      guarantee: 'Un empêchement ? Votre atelier peut être reporté jusqu’à 48 heures avant.',
      faq: [
        { q: 'Faut-il avoir déjà pratiqué ?', a: 'Pas du tout. L’atelier découverte est pensé pour les débutants.' },
        { q: 'Quand récupère-t-on sa pièce ?', a: 'Environ trois semaines après l’atelier, le temps du séchage et des cuissons.' },
        { q: 'Peut-on offrir un atelier ?', a: 'Oui : vous recevez un bon cadeau à imprimer, valable [durée].' },
        { q: 'Où se trouve l’atelier ?', a: '[Indiquez votre adresse, les horaires et comment venir.]' },
      ],
      finalTitle: 'La terre vous attend',
      finalText: 'Les ateliers ont lieu le [jour], en groupe de [nombre] personnes au plus.',
    },
    upsell: {
      title: 'Ajoutez un second atelier à prix doux',
      text: 'Revenez pour l’atelier « modelage » : une autre technique, la même ambiance.',
      bullets: ['Trois heures de modelage', 'Une seconde pièce à emporter', 'À réserver quand vous voulez'],
      accept: 'Oui, j’ajoute le second atelier',
      decline: 'Non merci, un seul me suffit',
    },
    thanks: {
      title: 'Merci {{first_name}}, c’est réservé !',
      lead: 'Nous avons hâte de vous accueillir. Voici ce qu’il faut savoir d’ici là.',
      steps: [
        ['Votre confirmation', 'Elle arrive par email, avec l’adresse et l’horaire.'],
        ['Le jour venu', 'Des vêtements qui ne craignent rien, et les ongles courts si possible.'],
        ['Après l’atelier', 'Nous vous écrivons dès que votre pièce sort du four.'],
      ],
    },
    webinar: {
      eyebrow: 'Rencontre en ligne',
      title: 'Dans les coulisses de l’atelier',
      lead: 'Une visite filmée en direct : le tour, le four, les émaux, et vos questions à l’artisan.',
      when: '[Jour et date] à [heure] — en ligne',
      points: [
        ['La terre', 'D’où elle vient et comment on la prépare.'],
        ['Le tour', 'Une pièce montée sous vos yeux.'],
        ['Le four', 'Ce qui se passe pendant la cuisson.'],
      ],
      hostName: 'Avec Margaux, céramiste',
      hostBio: '[Trois lignes : votre parcours d’artisan, ce que vous fabriquez et ce que vous aimez transmettre.]',
      cta: 'Je m’inscris à la visite',
    },
    soon: {
      eyebrow: 'Prochaine fournée',
      title: 'La nouvelle collection sort bientôt du four',
      lead: 'Les pièces sont en nombre limité. Inscrivez-vous pour être prévenu à l’ouverture de la boutique.',
      cta: 'Me prévenir',
    },
    voices: [
      { quote: '[Témoignage à remplacer] Ce que votre client a aimé pendant l’atelier.', name: 'Prénom N.', role: 'Participante' },
      { quote: '[Témoignage à remplacer] Ce qu’il a ressenti en récupérant sa pièce.', name: 'Prénom N.', role: 'Participant' },
      { quote: '[Témoignage à remplacer] Pour qui il recommande l’expérience.', name: 'Prénom N.', role: 'Participante' },
    ],
    emails: {
      welcome: {
        subject: 'Bienvenue à l’atelier',
        preheader: 'Le carnet arrive chaque mois, voici le premier.',
        title: 'Bienvenue, {{first_name}} !',
        body: 'Bonjour {{first_name}},\n\nMerci de rejoindre le carnet de l’atelier. Chaque mois, je vous écris depuis l’établi : les dates, les pièces, et un peu de la vie du four.',
        steps: ['Regardez les prochaines dates', 'Passez nous voir à la boutique', 'Répondez-moi pour toute question'],
        cta: 'Voir les prochaines dates',
      },
      newsletter: {
        subject: 'Le carnet de l’atelier — [mois]',
        preheader: 'Les dates, les pièces et un conseil d’artisan.',
        issue: 'Le carnet de l’atelier',
        title: 'Ce qui sort du four ce mois-ci',
        body: 'Bonjour {{first_name}},\n\nLe four a tourné toute la semaine. Au menu : une série de bols couleur sable, des dates d’ateliers pour le mois prochain, et une astuce pour vos théières.',
        cta: 'Voir les nouveautés',
        shorts: [['Les ateliers', 'Nouvelles dates : [dates].'], ['Le conseil', 'Pour garder un émail éclatant, évitez l’éponge abrasive.']],
        quote: 'Une belle pièce commence par une terre bien préparée.',
      },
      promo: {
        subject: 'Les ateliers du mois sont ouverts',
        preheader: 'Les places partent vite : réservez la vôtre.',
        eyebrow: 'Réservations ouvertes',
        title: 'De nouvelles dates à l’atelier',
        body: 'Bonjour {{first_name}},\n\nLes ateliers découverte du mois prochain sont ouverts à la réservation. Comme promis, vous êtes prévenu avant tout le monde.',
        points: ['Trois heures en petit groupe', 'Tout le matériel fourni', 'Votre pièce émaillée et cuite'],
        cta: 'Réserver mon atelier',
        ps: 'P.-S. L’atelier s’offre aussi : le bon cadeau est envoyé par email.',
      },
      reminder: {
        subject: 'Dernières places pour l’atelier',
        preheader: 'Il reste peu de tabourets libres.',
        body: 'Bonjour {{first_name}},\n\nIl reste quelques places pour les ateliers de ce mois. Si vous aviez prévu de venir, c’est le moment de réserver.',
        cta: 'Réserver mon atelier',
        ps: 'P.-S. Votre date peut être reportée jusqu’à 48 heures avant.',
      },
      webinar: {
        subject: 'Votre place pour la visite de l’atelier',
        preheader: 'Le lien et l’heure du direct.',
        title: 'C’est noté, {{first_name}} !',
        body: 'Bonjour {{first_name}},\n\nVous êtes inscrit à la visite en direct de l’atelier. Voici les informations pour nous retrouver.',
        tips: ['Préparez vos questions', 'Installez-vous avec une boisson chaude', 'La visite dure environ quarante minutes'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
