import type { KitDefinition } from './types';

/** Dark premium: an invitation card — near-black, brushed gold, thin frames, spaced capitals. */
export const nocturne: KitDefinition = {
  id: 'nocturne',
  name: 'Nocturne',
  pitch: 'Sombre et premium : noir profond, or brossé, cadres fins et capitales espacées, comme un carton d’invitation.',
  universe: 'Haut de gamme, cercle privé',
  goals: ['vente', 'lancement', 'webinaire'],
  tokens: {
    bg: '#0d0d10', alt: '#121216', surface: '#1a1a20', text: '#f1ede4', muted: '#aaa598',
    accent: '#d6b26e', accentText: '#14120d', accentInk: '#d6b26e', accent2: '#d6b26e', border: '#34343d',
    inverse: '#d6b26e', inverseText: '#14120d', inverseMuted: '#3a321f', inverseAccent: '#14120d',
    fontHeading: "'Playfair Display', Georgia, 'Times New Roman', serif", fontBody: "Outfit, 'Helvetica Neue', Arial, sans-serif",
    radius: 2, buttonRadius: 0, shadow: 'none', headingWeight: 500, headingSpacing: 0.2, buttonWeight: 600, buttonSpacing: 2.2, buttonCase: 'upper',
    h1: 58, h2: 38, lead: 19, space: 112, width: 960,
  },
  layout: {
    align: 'center', eyebrow: 'rule', header: 'center', hero: 'frame', benefits: 'numbered', proof: 'quote', offer: 'card', cta: 'band', footer: 'plain',
    art: 'deco', emailHeader: 'center', emailHero: 'plain',
  },
  copy: {
    brand: 'Maison Sélène',
    tagline: 'Le cercle des fondateurs exigeants',
    sign: 'Bien cordialement,\n**La Maison Sélène**',
    magnet: {
      eyebrow: 'Sur invitation',
      title: 'Recevez la note privée de la Maison',
      lead: 'Une fois par mois, une analyse réservée aux membres et à leurs invités. Rien de public, rien de superflu.',
      bullets: ['Une seule note par mois', 'Des cas réels, anonymisés', 'Réservée aux inscrits'],
      formTitle: 'Demander la note privée',
      cta: 'Recevoir la note',
      note: 'Votre adresse reste confidentielle.',
    },
    offer: {
      name: 'Le Cercle',
      eyebrow: 'Accompagnement sur candidature',
      title: 'Un cercle restreint pour décider à la hauteur de vos ambitions',
      lead: 'Douze mois, un petit nombre de membres, des rencontres à huis clos. Le Cercle s’adresse à ceux qui n’ont plus de pairs à qui parler.',
      cta: 'Déposer ma candidature',
      story: ['À un certain niveau, on décide seul', 'Vos équipes attendent des réponses, vos proches ne vivent pas vos enjeux. Le Cercle réunit des personnes qui portent des responsabilités comparables, dans un cadre où l’on peut tout dire.'],
      benefitsTitle: 'Ce que le Cercle vous apporte',
      benefits: [
        ['Des pairs, pas un public', 'Des échanges francs entre personnes qui vivent les mêmes arbitrages.'],
        ['Un regard extérieur', 'Un entretien individuel chaque mois pour prendre de la hauteur.'],
        ['Un cadre confidentiel', 'Ce qui se dit au Cercle ne sort pas du Cercle.'],
      ],
      programTitle: 'Une année au Cercle',
      program: [
        ['L’admission', 'Un entretien préalable pour vérifier que le Cercle vous convient, et réciproquement.'],
        ['Les rencontres', 'Une soirée à huis clos chaque mois, autour d’un cas apporté par un membre.'],
        ['Les entretiens', 'Un tête-à-tête mensuel, consacré à vos décisions en cours.'],
      ],
      includes: ['Douze rencontres à huis clos', 'Douze entretiens individuels', 'La note privée mensuelle', 'Deux journées de retraite dans l’année'],
      priceNote: 'pour l’année, sur candidature',
      guarantee: 'L’admission n’est définitive qu’après la première rencontre, pour vous comme pour nous.',
      faq: [
        { q: 'Qui peut candidater ?', a: '[Décrivez vos critères d’admission : fonction, taille d’activité, engagement attendu.]' },
        { q: 'Combien de membres compte le Cercle ?', a: 'Un nombre volontairement réduit, pour que chacun ait la parole.' },
        { q: 'Où ont lieu les rencontres ?', a: '[Indiquez le lieu, ou précisez si elles se tiennent en ligne.]' },
        { q: 'Comment se déroule la candidature ?', a: 'Un formulaire court, puis un entretien d’une demi-heure. Réponse sous une semaine.' },
      ],
      finalTitle: 'Les candidatures sont ouvertes',
      finalText: 'Les admissions se font une fois par an, dans la limite des places disponibles.',
    },
    upsell: {
      title: 'Ajoutez la retraite de printemps',
      text: 'Deux jours hors du temps avec les membres du Cercle, pour travailler votre cap à trois ans.',
      bullets: ['Deux jours en petit comité', 'Un lieu tenu confidentiel', 'Hébergement compris'],
      accept: 'Oui, je réserve ma place',
      decline: 'Non merci, je poursuis sans',
    },
    thanks: {
      title: 'Nous avons bien reçu votre demande',
      lead: 'Merci, {{first_name}}. Voici comment se déroule la suite.',
      steps: [
        ['Une confirmation écrite', 'Elle vous parvient par email dans les prochaines minutes.'],
        ['Un premier échange', 'Nous vous proposons un créneau d’entretien sous quelques jours.'],
        ['Votre réponse', 'Vous recevez notre décision, quelle qu’elle soit, sous une semaine.'],
      ],
    },
    webinar: {
      eyebrow: 'Soirée privée en ligne',
      title: 'Transmettre, céder, continuer : la conversation',
      lead: 'Une heure à huis clos avec trois membres du Cercle. Questions libres, aucun enregistrement.',
      when: '[Jour et date] à [heure] — sur invitation',
      points: [
        ['Les faits', 'Trois parcours, racontés sans fard.'],
        ['Les doutes', 'Ce qui ne se dit pas en public.'],
        ['Vos questions', 'La dernière demi-heure vous appartient.'],
      ],
      hostName: 'Reçue par [Prénom Nom]',
      hostBio: '[Trois lignes : votre parcours, votre rôle au sein de la Maison, l’esprit de ces soirées.]',
      cta: 'Demander une invitation',
    },
    soon: {
      eyebrow: 'Prochaine admission',
      title: 'Les candidatures rouvriront prochainement',
      lead: 'Inscrivez-vous pour être averti personnellement de l’ouverture.',
      cta: 'Être averti',
    },
    voices: [
      { quote: '[Témoignage à remplacer] Ce qu’un membre a trouvé au Cercle et nulle part ailleurs.', name: 'Prénom N.', role: 'Fondateur, secteur' },
      { quote: '[Témoignage à remplacer] Une décision prise grâce aux échanges.', name: 'Prénom N.', role: 'Dirigeante, secteur' },
      { quote: '[Témoignage à remplacer] Ce qu’il dirait à un pair.', name: 'Prénom N.', role: 'Associé, secteur' },
    ],
    emails: {
      welcome: {
        subject: 'Votre première note privée',
        preheader: 'Bienvenue parmi les lecteurs de la Maison.',
        title: 'Bienvenue, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nVous recevrez désormais la note privée de la Maison, une fois par mois. La première vous attend ci-dessous.',
        steps: ['Lisez la note à tête reposée', 'Gardez-la pour vous', 'Répondez-nous si un sujet vous concerne'],
        cta: 'Lire la note',
      },
      newsletter: {
        subject: 'La note privée — [mois]',
        preheader: 'Réservée aux membres et à leurs invités.',
        issue: 'La note privée',
        title: 'Savoir quand ne pas croître',
        body: 'Bonjour {{first_name}},\n\nOn mesure rarement ce qu’une croissance coûte à ceux qui la portent. Cette note examine trois situations où ralentir a été la décision la plus ambitieuse.',
        cta: 'Lire la note',
        shorts: [['Le cas du mois', 'Une cession refusée, et ce qui a suivi.'], ['À l’agenda', 'Prochaine rencontre : [date].']],
        quote: 'L’ambition se mesure aussi à ce qu’on refuse.',
      },
      promo: {
        subject: 'Les candidatures au Cercle sont ouvertes',
        preheader: 'Une admission par an, un nombre de places restreint.',
        eyebrow: 'Candidatures ouvertes',
        title: 'Le Cercle accueille de nouveaux membres',
        body: 'Bonjour {{first_name}},\n\nLes candidatures au Cercle sont ouvertes pour l’année à venir. Si vous lisez nos notes depuis quelque temps, vous savez déjà si ce cadre est le vôtre.',
        points: ['Douze rencontres à huis clos', 'Un entretien individuel chaque mois', 'Deux journées de retraite'],
        cta: 'Déposer ma candidature',
        ps: 'P.-S. L’admission n’est définitive qu’après la première rencontre.',
      },
      reminder: {
        subject: 'Clôture des candidatures',
        preheader: 'Dernier jour pour déposer la vôtre.',
        body: 'Bonjour {{first_name}},\n\nLes candidatures au Cercle seront closes ce soir. La prochaine admission aura lieu dans un an.',
        cta: 'Déposer ma candidature',
        ps: 'P.-S. Pour toute question, répondez simplement à ce message.',
      },
      webinar: {
        subject: 'Votre invitation est confirmée',
        preheader: 'Les informations pour nous rejoindre.',
        title: 'Votre invitation est confirmée',
        body: 'Bonjour {{first_name}},\n\nNous aurons le plaisir de vous accueillir à la soirée privée. Voici les informations utiles.',
        tips: ['La soirée n’est pas enregistrée', 'Préparez une question', 'Connectez-vous quelques minutes avant'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
