import type { KitDefinition } from './types';

/** SaaS / digital product: crisp interface look — cool whites, electric blue, soft cards, product mock. */
export const orbit: KitDefinition = {
  id: 'orbit',
  name: 'Orbite',
  pitch: 'Net et produit : blancs froids, bleu électrique, cartes douces et maquette d’interface.',
  universe: 'SaaS, produit numérique',
  goals: ['vente', 'lancement', 'webinaire'],
  tokens: {
    bg: '#ffffff', alt: '#f2f5fb', surface: '#ffffff', text: '#0b1324', muted: '#4f5b70',
    accent: '#2447f9', accentText: '#ffffff', accentInk: '#2447f9', accent2: '#00a884', border: '#dde4ef',
    inverse: '#0b1324', inverseText: '#f4f7fb', inverseMuted: '#a9b4c6', inverseAccent: '#8fb0ff',
    fontHeading: "Sora, 'Helvetica Neue', Arial, sans-serif", fontBody: "Manrope, 'Helvetica Neue', Arial, sans-serif",
    radius: 14, buttonRadius: 10, shadow: 'soft', headingWeight: 700, headingSpacing: -1.1, buttonWeight: 700,
    h1: 56, h2: 36, lead: 19, space: 96, width: 1080,
  },
  layout: {
    align: 'center', eyebrow: 'dot', header: 'bar', hero: 'center', benefits: 'grid', proof: 'cards', offer: 'two', cta: 'band', footer: 'plain',
    art: 'mock', emailHeader: 'left', emailHero: 'card',
  },
  copy: {
    brand: 'Orbite',
    tagline: 'Le planning partagé des petites équipes',
    sign: 'L’équipe Orbite',
    magnet: {
      eyebrow: 'Modèle gratuit',
      title: 'Le planning hebdomadaire qui tient sur un écran',
      lead: 'Le modèle que nous utilisons pour organiser la semaine d’une équipe de cinq. Prêt à copier.',
      bullets: ['Une vue par personne, une vue par projet', 'Les règles d’équipe qui vont avec', 'Compatible avec votre tableur'],
      formTitle: 'Recevoir le modèle',
      cta: 'Recevoir le modèle',
      note: 'Un seul email, avec le lien. Pas de relance commerciale.',
    },
    offer: {
      name: 'Orbite Équipe',
      eyebrow: 'Nouveau : les vues par projet',
      title: 'Toute la semaine de l’équipe, sur un seul écran',
      lead: 'Qui fait quoi, quand, et ce qui bloque. Orbite remplace le tableur partagé et la réunion du lundi.',
      cta: 'Démarrer maintenant',
      story: ['Le planning ne devrait pas être un second métier', 'Entre le tableur que personne ne met à jour et l’outil de gestion de projet trop lourd, il manque quelque chose de simple : une semaine lisible, tenue par l’équipe elle-même.'],
      benefitsTitle: 'Pensé pour les équipes de trois à vingt',
      benefits: [
        ['Une semaine lisible', 'Chaque personne voit sa charge et celle des autres, sans ouvrir dix onglets.'],
        ['Des blocages visibles', 'Un point rouge, un responsable, une date : rien ne reste en suspens.'],
        ['Zéro formation', 'On glisse, on dépose, c’est à jour pour tout le monde.'],
      ],
      programTitle: 'En place en une matinée',
      program: [
        ['Importez votre équipe', 'Un lien d’invitation, et chacun rejoint l’espace.'],
        ['Posez la semaine', 'Glissez les tâches dans les jours. Orbite signale les surcharges.'],
        ['Partagez la vue', 'Un lien en lecture seule pour vos clients ou votre direction.'],
      ],
      includes: ['Membres et projets illimités', 'Vues par personne et par projet', 'Partage en lecture seule', 'Export de vos données à tout moment', 'Assistance par email'],
      priceNote: 'par mois, sans engagement',
      guarantee: 'Résiliable à tout moment. Vos données restent exportables.',
      faq: [
        { q: 'Faut-il installer quelque chose ?', a: 'Non, Orbite fonctionne dans le navigateur, sur ordinateur comme sur téléphone.' },
        { q: 'Peut-on importer un planning existant ?', a: 'Oui, depuis un fichier CSV. Le modèle d’import est fourni.' },
        { q: 'Où sont hébergées les données ?', a: '[Précisez ici le lieu d’hébergement et vos engagements de confidentialité.]' },
        { q: 'Comment arrêter ?', a: 'Depuis les réglages, en deux clics. Vous pouvez exporter vos données avant.' },
      ],
      finalTitle: 'Lundi prochain, sans réunion de planning',
      finalText: 'Créez l’espace de votre équipe et posez votre première semaine en quelques minutes.',
    },
    upsell: {
      title: 'Passez à l’abonnement annuel',
      text: 'Réglez une fois pour l’année et gardez l’esprit libre : même produit, une seule facture.',
      bullets: ['Une facture unique pour l’année', 'Tarif préférentiel : [à préciser]', 'Assistance prioritaire'],
      accept: 'Oui, je passe à l’annuel',
      decline: 'Non merci, je reste au mois',
    },
    thanks: {
      title: 'Bienvenue à bord, {{first_name}}',
      lead: 'Votre espace est prêt. Trois étapes pour bien démarrer.',
      steps: [
        ['Confirmez votre adresse', 'Un email vient de partir avec votre lien d’accès.'],
        ['Invitez votre équipe', 'Partagez le lien d’invitation depuis les réglages.'],
        ['Posez votre première semaine', 'Commencez par les tâches déjà en cours.'],
      ],
    },
    webinar: {
      eyebrow: 'Démonstration en direct',
      title: 'Orbite en 30 minutes : de zéro à une semaine planifiée',
      lead: 'Une démonstration sur un cas réel, puis vos questions. Aucune installation nécessaire.',
      when: '[Jour et date] à [heure] — en ligne',
      points: [
        ['Mise en place', 'Créer l’espace et inviter l’équipe.'],
        ['La semaine type', 'Planifier, équilibrer, signaler un blocage.'],
        ['Le partage', 'Donner de la visibilité sans donner la main.'],
      ],
      hostName: 'Présentée par [Prénom Nom], équipe produit',
      hostBio: '[Deux ou trois lignes sur la personne qui anime : son rôle et ce qu’elle montrera pendant la démonstration.]',
      cta: 'Réserver ma place',
    },
    soon: {
      eyebrow: 'Bientôt disponible',
      title: 'Les vues par projet arrivent',
      lead: 'Inscrivez-vous pour tester la nouveauté avant tout le monde.',
      cta: 'Rejoindre la liste d’attente',
    },
    voices: [
      { quote: '[Témoignage à remplacer] Ce que l’équipe de votre client a arrêté de faire grâce au produit.', name: 'Prénom N.', role: 'Poste, entreprise' },
      { quote: '[Témoignage à remplacer] Le moment où le produit est devenu indispensable.', name: 'Prénom N.', role: 'Poste, entreprise' },
      { quote: '[Témoignage à remplacer] Un avant / après concret, sans chiffre inventé.', name: 'Prénom N.', role: 'Poste, entreprise' },
    ],
    emails: {
      welcome: {
        subject: 'Bienvenue sur Orbite',
        preheader: 'Votre espace est prêt : trois étapes pour démarrer.',
        title: 'Bienvenue, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nVotre espace Orbite est prêt. Le plus efficace est de poser dès maintenant la semaine en cours : dix minutes suffisent.',
        steps: ['Créez votre premier projet', 'Invitez deux collègues', 'Glissez trois tâches dans la semaine'],
        cta: 'Ouvrir mon espace',
      },
      newsletter: {
        subject: 'Nouveautés du mois : les vues par projet',
        preheader: 'Ce qui change dans Orbite, et comment en profiter.',
        issue: 'Les nouveautés du mois',
        title: 'Une vue par projet, enfin',
        body: 'Bonjour {{first_name}},\n\nVous pouviez voir la semaine par personne ; vous pouvez désormais la voir par projet. Même données, autre angle : pratique pour les points clients.',
        cta: 'Découvrir la nouveauté',
        shorts: [['Aussi ce mois-ci', 'L’export CSV inclut maintenant les commentaires.'], ['Astuce', 'Maintenez Maj pour déplacer plusieurs tâches d’un coup.']],
        quote: 'Un bon planning se lit en dix secondes.',
      },
      promo: {
        subject: 'Orbite Équipe est disponible',
        preheader: 'Toute la semaine de l’équipe sur un seul écran.',
        eyebrow: 'Disponible dès aujourd’hui',
        title: 'Orbite Équipe est là',
        body: 'Bonjour {{first_name}},\n\nOrbite Équipe est ouvert à tous. Si votre planning vit encore dans un tableur partagé, c’est le moment d’essayer autre chose.',
        points: ['Membres et projets illimités', 'Vues par personne et par projet', 'Résiliable à tout moment'],
        cta: 'Démarrer maintenant',
        ps: 'P.-S. Vos données restent exportables à tout moment.',
      },
      reminder: {
        subject: 'Votre espace vous attend',
        preheader: 'Dix minutes pour poser votre première semaine.',
        body: 'Bonjour {{first_name}},\n\nVous avez créé votre espace Orbite mais la semaine est encore vide. Posez trois tâches : vous verrez tout de suite si l’outil vous convient.',
        cta: 'Reprendre où j’en étais',
        ps: 'P.-S. Besoin d’un coup de main ? Répondez à cet email.',
      },
      webinar: {
        subject: 'Votre inscription à la démonstration',
        preheader: 'Date, lien de connexion et conseils.',
        title: 'C’est noté, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nVous êtes inscrit à la démonstration d’Orbite. Conservez cet email : le lien de connexion s’y trouve.',
        tips: ['Pensez à une semaine réelle de votre équipe', 'Préparez vos questions', 'La rediffusion est envoyée aux inscrits'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
