import type { KitDefinition } from './types';

/** Minimal editorial: a printed page — big serif with italics, numbered sections, hairlines, square buttons. */
export const revue: KitDefinition = {
  id: 'revue',
  name: 'Revue',
  pitch: 'Éditorial minimaliste : grand serif à italiques, sections numérotées, filets, angles droits.',
  universe: 'Auteur, newsletter, média',
  goals: ['capture', 'vente'],
  tokens: {
    bg: '#fcfbf8', alt: '#f2efe8', surface: '#ffffff', text: '#161513', muted: '#5c5850',
    accent: '#161513', accentText: '#fcfbf8', accentInk: '#a8321b', accent2: '#a8321b', border: '#d9d4c8',
    inverse: '#161513', inverseText: '#fcfbf8', inverseMuted: '#b9b3a6', inverseAccent: '#ece6d8',
    fontHeading: "Newsreader, Georgia, 'Times New Roman', serif", fontBody: "'Work Sans', 'Helvetica Neue', Arial, sans-serif",
    radius: 0, buttonRadius: 0, shadow: 'none', headingWeight: 500, headingSpacing: -0.8, buttonWeight: 600, buttonSpacing: 1.4, buttonCase: 'upper',
    h1: 66, h2: 38, lead: 20, space: 104, width: 880,
  },
  layout: {
    align: 'left', eyebrow: 'index', header: 'center', hero: 'editorial', benefits: 'numbered', proof: 'columns', offer: 'card', cta: 'line', footer: 'plain',
    art: 'figure', emailHeader: 'center', emailHero: 'plain',
  },
  copy: {
    brand: 'La Marge',
    tagline: 'Lettres sur l’art d’écrire clairement',
    sign: 'Bonne lecture,\n**Camille Aubert**',
    magnet: {
      eyebrow: 'La lettre',
      title: 'Écrire *moins*, dire *mieux*',
      lead: 'Un dimanche sur deux, une lettre courte sur le métier d’écrire : une idée, un exemple commenté, un exercice.',
      bullets: ['Une lettre, jamais plus de cinq minutes', 'Des exemples tirés de vrais textes', 'Un exercice à faire dans la semaine'],
      formTitle: 'S’abonner à la lettre',
      cta: 'Je m’abonne',
      note: 'Gratuit. On se désabonne d’un clic.',
    },
    offer: {
      name: 'L’Atelier en six lettres',
      eyebrow: 'L’atelier',
      title: 'Six lettres pour écrire des textes qu’on *lit jusqu’au bout*',
      lead: 'Un atelier d’écriture par correspondance : une leçon par semaine, un texte à rendre, un retour écrit sur chacun.',
      cta: 'S’inscrire à l’atelier',
      story: ['On ne vous a jamais appris à couper', 'À l’école, un bon texte était un texte long. Dans la vie, c’est l’inverse : on vous lit si vous êtes bref, précis et que chaque phrase mérite sa place. Cela s’apprend, en écrivant et en étant relu.'],
      benefitsTitle: 'Ce que l’atelier change dans vos textes',
      benefits: [
        ['Des débuts qui retiennent', 'Vous apprenez à commencer par ce qui compte, pas par ce qui précède.'],
        ['Des phrases qui portent', 'Un sujet, un verbe, une idée : la clarté comme politesse.'],
        ['Une voix reconnaissable', 'Vous repérez vos tics, vous gardez vos forces.'],
      ],
      programTitle: 'Six semaines, six lettres',
      program: [
        ['La première phrase', 'Pourquoi on vous quitte à la troisième ligne, et comment l’éviter.'],
        ['Couper', 'L’art de retirer un tiers du texte sans rien perdre.'],
        ['Le rythme', 'Alterner, relancer, conclure : la musique d’un paragraphe.'],
        ['Relire', 'Une méthode de relecture en trois passages.'],
      ],
      includes: ['Six leçons envoyées par lettre', 'Six exercices d’écriture', 'Un retour écrit sur chaque texte rendu', 'Le recueil des meilleurs textes de la promotion'],
      priceNote: 'pour les six semaines',
      guarantee: 'Remboursement intégral sur simple demande après la première lettre.',
      faq: [
        { q: 'Faut-il déjà écrire régulièrement ?', a: 'Non. Il faut avoir quelque chose à dire et accepter d’être relu.' },
        { q: 'Combien de temps par semaine ?', a: 'Une heure pour la leçon et l’exercice. Davantage si vous y prenez goût.' },
        { q: 'Qui relit les textes ?', a: '[Précisez qui assure les retours et dans quel délai.]' },
        { q: 'Peut-on suivre l’atelier à son rythme ?', a: 'Les lettres arrivent chaque semaine ; les exercices peuvent être rendus pendant deux mois.' },
      ],
      finalTitle: 'La prochaine promotion commence le [date]',
      finalText: 'Les retours étant écrits un par un, le nombre de places est limité.',
    },
    upsell: {
      title: 'Ajoutez une relecture *approfondie*',
      text: 'Envoyez un texte long de votre choix — article, chapitre, page de présentation — et recevez une relecture annotée.',
      bullets: ['Un texte jusqu’à [nombre] signes', 'Annotations ligne à ligne', 'Un entretien de trente minutes pour en parler'],
      accept: 'Oui, j’ajoute la relecture',
      decline: 'Non merci, l’atelier me suffit',
    },
    thanks: {
      title: 'Merci, {{first_name}}.',
      lead: 'Votre inscription est enregistrée. La suite tient en trois lignes.',
      steps: [
        ['Confirmez votre adresse', 'Un email vient de partir : un clic suffit.'],
        ['Lisez la lettre d’accueil', 'Elle explique le fonctionnement et le calendrier.'],
        ['Préparez un carnet', 'On écrit mieux quand on a d’abord écrit à la main.'],
      ],
    },
    webinar: {
      eyebrow: 'Lecture publique',
      title: 'Couper un texte *en direct*',
      lead: 'Une heure de travail sur un texte envoyé par une lectrice. On coupe, on réécrit, on compare.',
      when: '[Jour et date] à [heure] — en ligne',
      points: [
        ['Lire', 'Repérer ce que le texte veut dire, vraiment.'],
        ['Couper', 'Retirer sans appauvrir.'],
        ['Réécrire', 'Trois versions de la première phrase.'],
      ],
      hostName: 'Avec Camille Aubert',
      hostBio: '[Trois lignes : ce que vous écrivez, où l’on peut vous lire, ce que vous transmettez dans vos ateliers.]',
      cta: 'Réserver ma place',
    },
    soon: {
      eyebrow: 'À paraître',
      title: 'Un *nouveau* cycle de lettres se prépare',
      lead: 'Les abonnés à la liste d’attente reçoivent le sommaire avant tout le monde.',
      cta: 'Être prévenu',
    },
    voices: [
      { quote: '[Témoignage à remplacer] Ce qu’une lectrice écrit différemment depuis l’atelier.', name: 'Prénom N.', role: 'Son activité' },
      { quote: '[Témoignage à remplacer] Une phrase précise sur la qualité des retours.', name: 'Prénom N.', role: 'Son activité' },
      { quote: '[Témoignage à remplacer] Ce qu’elle en dirait à un ami.', name: 'Prénom N.', role: 'Son activité' },
    ],
    emails: {
      welcome: {
        subject: 'Bienvenue dans La Marge',
        preheader: 'Comment lire cette lettre, et quoi en attendre.',
        title: 'Bienvenue, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nMerci de vous être abonné. La Marge paraît un dimanche sur deux. Chaque lettre tient une promesse simple : vous faire écrire un peu mieux la semaine suivante.',
        steps: ['Lisez la lettre le jour même', 'Faites l’exercice avant mercredi', 'Répondez-moi si une idée vous résiste'],
        cta: 'Lire la première lettre',
      },
      newsletter: {
        subject: 'La Marge n° [numéro] — la phrase de trop',
        preheader: 'Celle qu’on aime le plus est souvent celle qu’il faut retirer.',
        issue: 'Lettre n° [numéro]',
        title: 'La phrase *de trop*',
        body: 'Bonjour {{first_name}},\n\nDans chaque texte, il y a une phrase dont on est fier. C’est presque toujours elle qui gêne. Cette lettre explique comment la reconnaître, et pourquoi la retirer fait du bien au reste.',
        cta: 'Lire la lettre entière',
        shorts: [['L’exemple', 'Un paragraphe avant et après coupe, commenté.'], ['L’exercice', 'Retirez la meilleure phrase de votre dernier texte.']],
        quote: 'Écrire, c’est choisir ce qu’on ne dira pas.',
      },
      promo: {
        subject: 'L’Atelier en six lettres rouvre',
        preheader: 'Six semaines, six textes, six retours écrits.',
        eyebrow: 'Inscriptions ouvertes',
        title: 'L’Atelier *rouvre* ses portes',
        body: 'Bonjour {{first_name}},\n\nLes inscriptions à l’Atelier en six lettres sont ouvertes. Si vous voulez écrire des textes qu’on lit jusqu’au bout, c’est le format le plus direct que je connaisse.',
        points: ['Une leçon par semaine', 'Un exercice à rendre', 'Un retour écrit sur chaque texte'],
        cta: 'S’inscrire à l’atelier',
        ps: 'P.-S. Remboursement sur simple demande après la première lettre.',
      },
      reminder: {
        subject: 'Dernières places pour l’atelier',
        preheader: 'Les inscriptions ferment demain.',
        body: 'Bonjour {{first_name}},\n\nLes inscriptions à l’atelier ferment demain soir. Je n’ajoute pas de places : chaque texte est relu à la main.',
        cta: 'S’inscrire à l’atelier',
        ps: 'P.-S. Une hésitation ? Répondez à cette lettre, je vous lirai.',
      },
      webinar: {
        subject: 'Votre place pour la lecture publique',
        preheader: 'Le lien, l’heure, et une chose à préparer.',
        title: 'Votre place est *réservée*',
        body: 'Bonjour {{first_name}},\n\nVous êtes inscrit à la lecture publique. Voici les informations pratiques.',
        tips: ['Apportez un court texte à vous', 'Un crayon vaut mieux qu’un clavier', 'La rediffusion sera envoyée aux inscrits'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
