import type { KitDefinition } from './types';

/** Event / webinar: a concert poster — night indigo, magenta, stage-light yellow, condensed capitals. */
export const scene: KitDefinition = {
  id: 'scene',
  name: 'Scène',
  pitch: 'Affiche d’événement : indigo nuit, magenta, jaune projecteur et capitales condensées.',
  universe: 'Événement, webinaire, conférence',
  goals: ['webinaire', 'lancement', 'capture'],
  tokens: {
    bg: '#fff7ea', alt: '#ffeccd', surface: '#ffffff', text: '#1b1035', muted: '#54476f',
    accent: '#d8125f', accentText: '#ffffff', accentInk: '#b80e50', accent2: '#ffc53d', border: '#e4cfa8',
    inverse: '#1b1035', inverseText: '#fff7ea', inverseMuted: '#c3b8dc', inverseAccent: '#ffc53d',
    fontHeading: "Oswald, 'Arial Narrow', Arial, sans-serif", fontBody: "'Plus Jakarta Sans', 'Helvetica Neue', Arial, sans-serif",
    radius: 4, buttonRadius: 4, shadow: 'none', headingWeight: 700, headingSpacing: 0.4, headingCase: 'upper', buttonWeight: 800, buttonSpacing: 1.2, buttonCase: 'upper',
    h1: 76, h2: 44, lead: 19, space: 88, width: 1080,
  },
  layout: {
    align: 'left', eyebrow: 'caps', header: 'inverse', hero: 'poster', benefits: 'cards', proof: 'cards', offer: 'card', cta: 'band', footer: 'inverse',
    art: 'rays', emailHeader: 'band', emailHero: 'band',
  },
  copy: {
    brand: 'Les Rencontres du Numérique',
    tagline: 'Deux jours de conférences en ligne pour les indépendants',
    sign: 'À très bientôt,\n**L’équipe des Rencontres**',
    magnet: {
      eyebrow: 'Programme complet',
      title: 'Recevez le programme des Rencontres',
      lead: 'Les conférences, les horaires et les intervenants, dans un seul document à garder sous la main.',
      bullets: ['Le détail des deux journées', 'Les thèmes de chaque conférence', 'Les horaires des ateliers pratiques'],
      formTitle: 'Recevoir le programme',
      cta: 'Envoyez-moi le programme',
      note: 'Vous recevrez aussi les rappels avant l’événement.',
    },
    offer: {
      name: 'le Pass Rediffusion',
      eyebrow: 'Pass rediffusion',
      title: 'Toutes les conférences, à revoir quand vous voulez',
      lead: 'Le direct est gratuit. Le pass vous donne les enregistrements, les supports des intervenants et les ateliers en petit groupe.',
      cta: 'Prendre mon pass',
      story: ['Deux jours, c’est court', 'Vous ne pourrez pas tout suivre en direct : un client qui appelle, un atelier qui chevauche une conférence. Le pass vous permet de tout revoir, à votre rythme, avec les documents sous les yeux.'],
      benefitsTitle: 'Ce que le pass débloque',
      benefits: [
        ['Les rediffusions', 'Chaque conférence, disponible dès le lendemain.'],
        ['Les supports', 'Les présentations et les modèles partagés par les intervenants.'],
        ['Les ateliers', 'Des sessions pratiques en petit groupe, réservées aux détenteurs du pass.'],
      ],
      programTitle: 'Au programme',
      program: [
        ['Jour 1 — Trouver ses clients', 'Positionnement, offre et prospection sans publicité.'],
        ['Jour 1 — Ateliers', 'Travail en petit groupe sur votre propre offre.'],
        ['Jour 2 — Vendre et fidéliser', 'Pages de vente, emails et suivi client.'],
        ['Jour 2 — Table ronde', 'Questions libres aux intervenants.'],
      ],
      includes: ['Les enregistrements de toutes les conférences', 'Les supports des intervenants', 'L’accès aux ateliers pratiques', 'Les rediffusions disponibles pendant [durée]'],
      priceNote: 'tarif unique',
      guarantee: 'Remboursement sur simple demande jusqu’à la veille de l’événement.',
      faq: [
        { q: 'Le direct est-il vraiment gratuit ?', a: 'Oui. L’inscription gratuite donne accès à toutes les conférences en direct.' },
        { q: 'Combien de temps ai-je accès aux rediffusions ?', a: '[Précisez la durée d’accès aux enregistrements.]' },
        { q: 'Les ateliers sont-ils enregistrés ?', a: 'Non : ils se déroulent en petit groupe et ne sont pas rediffusés.' },
        { q: 'Puis-je obtenir une facture ?', a: 'Oui, elle vous est envoyée par email après le paiement.' },
      ],
      finalTitle: 'Ne manquez aucune conférence',
      finalText: 'Le pass est disponible jusqu’au dernier jour de l’événement.',
    },
    upsell: {
      title: 'Ajoutez la séance de questions privée',
      text: 'Une heure en comité réduit avec deux intervenants, après l’événement, pour parler de votre cas.',
      bullets: ['Un groupe de [nombre] personnes au plus', 'Vos questions traitées une à une', 'Un compte rendu envoyé ensuite'],
      accept: 'Oui, j’ajoute la séance',
      decline: 'Non merci, le pass me suffit',
    },
    thanks: {
      title: 'Vous êtes inscrit, {{first_name}} !',
      lead: 'Votre place est réservée. Voici comment préparer votre venue.',
      steps: [
        ['Votre confirmation', 'Un email vient de partir avec votre lien d’accès.'],
        ['L’agenda', 'Ajoutez les deux journées à votre calendrier.'],
        ['Le programme', 'Repérez les conférences que vous ne voulez pas manquer.'],
      ],
    },
    webinar: {
      eyebrow: 'Conférences en ligne · gratuit',
      title: 'Les Rencontres du Numérique',
      lead: 'Deux jours, des conférences courtes et des ateliers pratiques pour développer votre activité d’indépendant.',
      when: '[Dates de l’événement] — en ligne, en direct',
      points: [
        ['Des formats courts', 'Trente minutes par conférence, puis vos questions.'],
        ['Du concret', 'Des méthodes montrées sur des cas réels.'],
        ['Des ateliers', 'Pour repartir avec quelque chose de fait.'],
      ],
      hostName: 'Organisé par [Votre nom ou structure]',
      hostBio: '[Trois lignes : qui organise l’événement, pour qui, et ce qui le distingue.]',
      cta: 'Je réserve ma place',
    },
    soon: {
      eyebrow: 'Prochaine édition',
      title: 'La prochaine édition se prépare',
      lead: 'Inscrivez-vous pour recevoir les dates et le programme dès leur annonce.',
      cta: 'Me tenir informé',
    },
    voices: [
      { quote: '[Témoignage à remplacer] Ce qu’un participant a appliqué dès le lendemain.', name: 'Prénom N.', role: 'Participant, métier' },
      { quote: '[Témoignage à remplacer] La conférence qui l’a le plus marqué, et pourquoi.', name: 'Prénom N.', role: 'Participante, métier' },
      { quote: '[Témoignage à remplacer] Ce qu’il dirait à quelqu’un qui hésite à s’inscrire.', name: 'Prénom N.', role: 'Participant, métier' },
    ],
    emails: {
      welcome: {
        subject: 'Le programme des Rencontres',
        preheader: 'Deux jours de conférences : tout est là.',
        title: 'Bienvenue, {{first_name}}',
        body: 'Bonjour {{first_name}},\n\nMerci de votre inscription. Le programme complet est disponible ci-dessous. Prenez cinq minutes pour repérer vos conférences.',
        steps: ['Parcourez le programme', 'Notez trois conférences à ne pas manquer', 'Ajoutez les dates à votre agenda'],
        cta: 'Voir le programme',
      },
      newsletter: {
        subject: 'Les Rencontres : les intervenants se dévoilent',
        preheader: 'Nouvelles conférences et coulisses de l’organisation.',
        issue: 'Le journal des Rencontres',
        title: 'Trois nouvelles conférences au programme',
        body: 'Bonjour {{first_name}},\n\nLe programme s’étoffe. Cette semaine, nous annonçons trois nouvelles conférences et l’ouverture des inscriptions aux ateliers.',
        cta: 'Voir le programme à jour',
        shorts: [['Les ateliers', 'Places limitées : réservation ouverte aux détenteurs du pass.'], ['En coulisses', 'Comment nous choisissons les intervenants.']],
        quote: 'Une bonne conférence tient en une idée qu’on applique le lendemain.',
      },
      promo: {
        subject: 'Le Pass Rediffusion est disponible',
        preheader: 'Revoyez toutes les conférences à votre rythme.',
        eyebrow: 'Pass rediffusion',
        title: 'Ne manquez aucune conférence',
        body: 'Bonjour {{first_name}},\n\nVous ne pourrez pas tout suivre en direct, et c’est normal. Le pass vous donne les enregistrements, les supports et l’accès aux ateliers.',
        points: ['Toutes les rediffusions', 'Les supports des intervenants', 'Les ateliers en petit groupe'],
        cta: 'Prendre mon pass',
        ps: 'P.-S. Remboursement sur simple demande jusqu’à la veille de l’événement.',
      },
      reminder: {
        subject: 'C’est demain !',
        preheader: 'Votre lien et les horaires de la première journée.',
        body: 'Bonjour {{first_name}},\n\nLes Rencontres commencent demain. Votre lien d’accès est le même pour les deux journées : gardez cet email sous la main.',
        cta: 'Accéder à l’événement',
        ps: 'P.-S. Le pass rediffusion reste disponible jusqu’à la fin de l’événement.',
      },
      webinar: {
        subject: 'Votre place aux Rencontres est réservée',
        preheader: 'Dates, lien d’accès et conseils pratiques.',
        title: 'Votre place est réservée',
        body: 'Bonjour {{first_name}},\n\nVous êtes inscrit aux Rencontres du Numérique. Voici tout ce qu’il faut pour en profiter.',
        tips: ['Choisissez vos conférences à l’avance', 'Prévoyez de quoi prendre des notes', 'Testez votre connexion la veille'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
