import type { KitDefinition } from './types';

/** Course creator: loud and friendly — thick black outlines, offset shadows, vermilion on sunflower yellow. */
export const studio: KitDefinition = {
  id: 'studio',
  name: 'Studio',
  pitch: 'Énergique : contours noirs épais, ombres décalées, vermillon sur jaune tournesol.',
  universe: 'Créateur de formation',
  goals: ['vente', 'lancement', 'capture'],
  tokens: {
    bg: '#fffdf6', alt: '#ffe45c', surface: '#ffffff', text: '#141414', muted: '#3d3a33',
    accent: '#ff4d2e', accentText: '#141414', accentInk: '#ad2308', accent2: '#6c4dff', border: '#141414',
    inverse: '#141414', inverseText: '#fffdf6', inverseMuted: '#c9c5b8', inverseAccent: '#ffe45c',
    fontHeading: "'Bricolage Grotesque', 'Arial Black', Arial, sans-serif", fontBody: "'DM Sans', 'Helvetica Neue', Arial, sans-serif",
    radius: 14, buttonRadius: 12, borderWidth: 2, shadow: 'hard', headingWeight: 800, headingSpacing: -1.2, buttonWeight: 800,
    h1: 64, h2: 40, lead: 20, space: 88, width: 1080,
  },
  layout: {
    align: 'center', eyebrow: 'star', header: 'bar', hero: 'block', benefits: 'cards', proof: 'cards', offer: 'two', cta: 'boxed', footer: 'inverse',
    art: 'shapes', emailHeader: 'band', emailHero: 'card',
  },
  copy: {
    brand: 'Atelier Déclic',
    tagline: 'Des formations en ligne qu’on termine',
    sign: 'À très vite,\n**Léo, de l’Atelier Déclic**',
    magnet: {
      eyebrow: 'Checklist gratuite',
      title: 'Tournez votre première leçon vidéo ce week-end',
      lead: 'La liste exacte du matériel, du plan et des réglages. Rien à acheter, rien à installer.',
      bullets: ['Le plan d’une leçon en cinq blocs', 'Les réglages son et lumière avec un téléphone', 'La trame du script, prête à remplir'],
      formTitle: 'Je veux la checklist',
      cta: 'Envoyez-moi la checklist',
      note: 'Zéro spam. Désinscription en un clic.',
    },
    offer: {
      name: 'Formation Express',
      eyebrow: 'Nouvelle promotion',
      title: 'Créez votre formation en ligne en 30 jours, pour de bon',
      lead: 'Un sprint guidé, semaine après semaine : vous sortez avec une formation enregistrée, une page de vente et vos premiers inscrits.',
      cta: 'Je rejoins le sprint',
      story: ['Votre formation existe déjà. Elle est juste coincée dans votre tête.', 'Vous avez le savoir-faire, des notes partout et trois plans commencés. Ce qui manque, c’est un calendrier, des étapes courtes et quelqu’un pour vous dire « c’est assez bien, on publie ».'],
      benefitsTitle: 'Ce que vous aurez dans 30 jours',
      benefits: [
        ['Une formation enregistrée', 'Pas un plan, pas un brouillon : des leçons tournées et montées.'],
        ['Une page qui vend', 'Votre promesse, votre programme et votre prix, en ligne.'],
        ['Vos premiers élèves', 'Une méthode de lancement à petite échelle, sans publicité.'],
      ],
      programTitle: 'Quatre semaines, quatre livrables',
      program: [
        ['Semaine 1 — La promesse', 'Vous choisissez un sujet étroit et un résultat précis pour vos élèves.'],
        ['Semaine 2 — Le plan', 'Vous découpez le parcours en leçons courtes, exercices compris.'],
        ['Semaine 3 — Le tournage', 'Vous enregistrez en lots, avec le matériel que vous avez.'],
        ['Semaine 4 — Le lancement', 'Vous ouvrez les inscriptions à une première promotion.'],
      ],
      includes: ['Le parcours complet en vidéo', 'Les modèles de plan, script et page de vente', 'Un atelier en direct chaque semaine', 'Le groupe d’entraide de la promotion', 'La relecture de votre page de vente'],
      priceNote: 'accès à vie',
      guarantee: 'Satisfait ou remboursé pendant 14 jours, sans justification.',
      faq: [
        { q: 'Je n’ai pas encore de sujet précis. C’est grave ?', a: 'Non : la première semaine sert exactement à le choisir, avec une méthode pour le tester.' },
        { q: 'Combien de temps par semaine ?', a: 'Comptez cinq à six heures, réparties comme vous voulez.' },
        { q: 'Faut-il du matériel vidéo ?', a: 'Un téléphone récent et une fenêtre suffisent. Tout est détaillé dans le parcours.' },
        { q: 'Et si je prends du retard ?', a: 'Vous gardez l’accès au parcours et aux rediffusions des ateliers.' },
      ],
      finalTitle: 'Dans 30 jours, elle est en ligne.',
      finalText: 'La prochaine promotion démarre le [date]. Les ateliers se font en petit groupe.',
    },
    upsell: {
      title: 'Ajoutez le pack de modèles de montage',
      text: 'Génériques, titres et transitions prêts à l’emploi : vous montez une leçon en vingt minutes.',
      bullets: ['Douze modèles de génériques et de titres', 'Compatibles avec les logiciels gratuits', 'Le tutoriel pas à pas'],
      accept: 'Oui, j’ajoute le pack',
      decline: 'Non merci, je continue sans',
    },
    thanks: {
      title: 'C’est parti, {{first_name}} !',
      lead: 'Votre inscription est validée. Voici les trois choses à faire maintenant.',
      steps: [
        ['Ouvrez votre boîte mail', 'Vos accès viennent de partir. Vérifiez aussi les courriers indésirables.'],
        ['Présentez-vous', 'Dites bonjour dans le groupe : votre sujet, votre échéance.'],
        ['Bloquez vos créneaux', 'Notez dans votre agenda vos deux plages de travail de la semaine.'],
      ],
    },
    webinar: {
      eyebrow: 'Atelier gratuit en direct',
      title: 'Le plan d’une formation qui se vend, en 45 minutes',
      lead: 'On construit un plan ensemble, en direct, à partir d’un vrai sujet. Venez avec le vôtre.',
      when: '[Jour et date] à [heure] — en direct',
      points: [
        ['Un sujet étroit', 'Pourquoi « tout sur… » ne se vend pas, et quoi faire à la place.'],
        ['Un résultat promis', 'La phrase qui fait dire « c’est pour moi ».'],
        ['Un parcours court', 'Le découpage en leçons de dix minutes.'],
      ],
      hostName: 'Avec Léo, fondateur de l’Atelier Déclic',
      hostBio: '[Trois lignes sur vous : ce que vous enseignez, depuis quand, et pourquoi on peut vous faire confiance sur ce sujet.]',
      cta: 'Je réserve ma place',
    },
    soon: {
      eyebrow: 'Ouverture prochaine',
      title: 'La prochaine promotion arrive',
      lead: 'Les inscrits à la liste d’attente sont prévenus en premier, avant l’ouverture publique.',
      cta: 'Je rejoins la liste d’attente',
    },
    voices: [
      { quote: '[Témoignage à remplacer] Ce que votre élève a publié grâce à la formation, en une phrase.', name: 'Prénom N.', role: 'Son métier' },
      { quote: '[Témoignage à remplacer] Le blocage qu’il avait avant, et ce qui l’a levé.', name: 'Prénom N.', role: 'Son métier' },
      { quote: '[Témoignage à remplacer] Ce qu’il recommande à quelqu’un qui hésite.', name: 'Prénom N.', role: 'Son métier' },
    ],
    emails: {
      welcome: {
        subject: 'Votre checklist est là',
        preheader: 'Et un défi pour ce week-end.',
        title: 'Salut {{first_name}}, on s’y met ?',
        body: 'Bonjour {{first_name}},\n\nLa checklist est juste en dessous. Mon conseil : ne la lisez pas, faites-la. Un samedi matin, un téléphone, une leçon de cinq minutes.',
        steps: ['Choisissez une seule notion à expliquer', 'Tournez une prise, sans la refaire', 'Envoyez-la à une personne de confiance'],
        cta: 'Ouvrir la checklist',
      },
      newsletter: {
        subject: 'Une leçon de dix minutes vaut mieux qu’un module parfait',
        preheader: 'Le conseil de la semaine pour avancer sur votre formation.',
        issue: 'Le mémo du jeudi',
        title: 'Publiez petit, publiez tôt',
        body: 'Bonjour {{first_name}},\n\nLa meilleure façon de finir une formation, c’est d’en publier un morceau. Cette semaine : comment transformer une seule leçon en mini-cours d’appel.',
        cta: 'Lire la méthode',
        shorts: [['Le modèle', 'La trame de script en cinq blocs, à copier.'], ['L’exercice', 'Résumez votre promesse en douze mots.']],
        quote: 'Fait vaut mieux que parfait, surtout quand c’est en ligne.',
      },
      promo: {
        subject: 'Les inscriptions sont ouvertes',
        preheader: 'La promotion démarre le [date].',
        eyebrow: 'C’est ouvert',
        title: 'Formation Express : 30 jours pour publier',
        body: 'Bonjour {{first_name}},\n\nLa nouvelle promotion de Formation Express est ouverte. Quatre semaines, quatre livrables, et une formation en ligne à la fin.',
        points: ['Un parcours guidé semaine après semaine', 'Un atelier en direct chaque semaine', 'La relecture de votre page de vente'],
        cta: 'Je rejoins le sprint',
        ps: 'P.-S. Satisfait ou remboursé pendant 14 jours.',
      },
      reminder: {
        subject: 'Fermeture des inscriptions ce soir',
        preheader: 'Dernier rappel, promis.',
        body: 'Bonjour {{first_name}},\n\nLes inscriptions à Formation Express ferment ce soir à minuit. Si vous attendiez le bon moment : c’est celui-ci.',
        cta: 'Je rejoins le sprint',
        ps: 'P.-S. Une question avant de vous décider ? Répondez à cet email.',
      },
      webinar: {
        subject: 'C’est réservé : à [jour] !',
        preheader: 'Votre lien pour l’atelier en direct.',
        title: 'Votre place est réservée',
        body: 'Bonjour {{first_name}},\n\nVous êtes inscrit à l’atelier « Le plan d’une formation qui se vend ». Gardez cet email : il contient votre lien.',
        tips: ['Venez avec un sujet en tête', 'Prévoyez de quoi noter', 'Arrivez cinq minutes avant le début'],
        cta: 'Ajouter à mon agenda',
      },
    },
  },
};
